In [1]:
import pandas as pd

df = pd.read_csv("../data/superstore.csv")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.582
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,NaN,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,NaN,-383.031
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,NaN,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,$2.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3.00,0.2,4.1028
9997,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.0,15.6332
9998,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,NaN,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9999,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6,4,0.0,13.32
10000,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [2]:
df.info()
print(df.shape)
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10001 non-null  int64
 1   Order ID       10001 non-null  object
 2   Order Date     10001 non-null  object
 3   Ship Date      10001 non-null  object
 4   Ship Mode      10001 non-null  object
 5   Customer ID    10001 non-null  object
 6   Customer Name  9617 non-null   object
 7   Segment        10001 non-null  object
 8   Country        10001 non-null  object
 9   City           9602 non-null   object
 10  State          9618 non-null   object
 11  Postal Code    9597 non-null   float64
 12  Region         10001 non-null  object
 13  Product ID     10001 non-null  object
 14  Category       10001 non-null  object
 15  Sub-Category   10001 non-null  object
 16  Product Name   9595 non-null   object
 17  Sales          10001 non-null  object
 18  Quantity       10001 non-null  object
 19  Discount       9632 non-null   float64
 20  Profit         10001 non-null  object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.6+ MB
(10001, 21)

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name    384
Segment            0
Country            0
City             399
State            383
Postal Code      404
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name     406
Sales              0
Quantity           0
Discount         369
Profit             0
dtype: int64

In [3]:
df.describe()

             Row ID   Postal Code     Discount
count  10001.000000   9597.000000  9632.000000
mean    4997.045495  55187.283630     0.157256
std     2884.832844  32047.913896     0.207503
min        1.000000   1040.000000     0.000000
25%     2499.000000  23223.000000     0.000000
50%     4998.000000  56301.000000     0.200000
75%     7494.000000  90008.000000     0.200000
max     9994.000000  99301.000000     0.800000

Due to the missing values of City represent less than 4% of the total data, we will drop the rows with missing values in the City column.

In [4]:
df = df.dropna(subset=['City'])
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.582
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7,0.0,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.28,4,0.0,1.9656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9989,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605.0,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1,5,0.0,55.647
9996,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3.00,0.2,4.1028
9997,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.0,15.6332
9999,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6,4,0.0,13.32
10000,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [5]:
df.isna().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name    378
Segment            0
Country            0
City               0
State            371
Postal Code      390
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name     375
Sales              0
Quantity           0
Discount         353
Profit             0
dtype: int64

The missing values of Column name still in the dataset due to ......

In [6]:
df_final = df.copy()
df_final['Customer Name'] = df_final['Customer Name'].fillna('Unknown')

In [7]:
df_final.isna().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City               0
State            371
Postal Code      390
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name     375
Sales              0
Quantity           0
Discount         353
Profit             0
dtype: int64

In [8]:
df2 = df_final.copy()

# Convert Dates
df2['Order Date'] = pd.to_datetime(df2['Order Date'], format= 'mixed')
df2['Ship Date'] = pd.to_datetime(df2['Ship Date'], format= 'mixed')


# Convert Financials (Cleaning strings like '$1,200.00' first)
df2['Sales'] = pd.to_numeric(df2['Sales'].replace(r'[\$,]', '', regex=True), errors='coerce')
df2['Profit'] = pd.to_numeric(df2['Profit'].replace(r'[\$,]', '', regex=True), errors='coerce')

# Convert Quantity to Integer
df2['Quantity'] = pd.to_numeric(df2['Quantity'], errors='coerce').fillna(0).astype(int)

# Clean up Postal Code (removing decimal .0 and treating as string)
df2['Postal Code'] = df2['Postal Code'].fillna(0).astype(int).astype(str)

# Optimize Categorical columns
categorical_cols = ['Ship Mode', 'Segment', 'Region', 'Category', 'Sub-Category']
df2[categorical_cols] = df2[categorical_cols].astype('category')

# Verify the changes
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
Index: 9602 entries, 0 to 10000
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9602 non-null   int64
 1   Order ID       9602 non-null   object
 2   Order Date     9602 non-null   datetime64[ns]
 3   Ship Date      9602 non-null   datetime64[ns]
 4   Ship Mode      9602 non-null   category
 5   Customer ID    9602 non-null   object
 6   Customer Name  9602 non-null   object
 7   Segment        9602 non-null   category
 8   Country        9602 non-null   object
 9   City           9602 non-null   object
 10  State          9231 non-null   object
 11  Postal Code    9602 non-null   object
 12  Region         9602 non-null   category
 13  Product ID     9602 non-null   object
 14  Category       9602 non-null   category
 15  Sub-Category   9602 non-null   category
 16  Product Name   9227 non-null   object
 17  Sales          9525 non-null   float64
 18  Quantity       9602 non-null   int64
 19  Discount       9249 non-null   float64
 20  Profit         9529 non-null   float64
dtypes: category(5), datetime64[ns](2), float64(3), int64(2), object(9)
memory usage: 1.3+ MB
None

In [9]:
# Check for any dates that couldn't be parsed at all
print(f"Missing Order Dates: {df2['Order Date'].isna().sum()}")
print(f"Missing Ship Dates: {df2['Ship Date'].isna().sum()}")

Missing Order Dates: 0
Missing Ship Dates: 0

In [10]:
#10

In [11]:
#11

In [12]:
#12

In [13]:
#13

In [14]:
#14

In [15]:
#15

In [16]:
#16

In [17]:
#17

In [18]:
#18

In [19]:
#19

In [20]:
#20

In [21]:
#21

In [22]:
#22

In [23]:
#23

In [24]:
#24

In [25]:
#25

In [26]:
#26

In [27]:
#27

In [28]:
#28

In [29]:
#29

In [30]:
#30

### Segment Based Analysis

In [31]:
def compare_segments(df, seg_a, seg_b, start=None, end=None):

    # Define the segment mask
    mask = df['Segment'].isin([seg_a, seg_b])
    
    # Add optional Date filtering
    if start or end:
        start_dt = pd.to_datetime(start) if start else df['Order Date'].min()
        end_dt = pd.to_datetime(end) if end else df['Order Date'].max()
        
        lower = min(start_dt, end_dt)
        upper = max(start_dt, end_dt)
        
        mask = mask & (df['Order Date'] >= lower) & (df['Order Date'] <= upper)

        print( ' Analysis Period: ' + lower.strftime('%Y-%m-%d') + ' to ' + upper.strftime('%Y-%m-%d') + ' ')   
    else:    
        print(' Analysis Period: Full Dataset  ')
    
    df_filtered = df.loc[mask]
        

    # Aggregate all four required metrics
    comparison = df_filtered.groupby('Segment', observed=True).agg(
        Avg_Sales=('Sales', 'mean'),
        Total_Sales=('Sales', 'sum'),
        Avg_Profit=('Profit', 'mean'),
        Total_Profit=('Profit', 'sum')
    )

    # Calculate the Difference
    if len(comparison) >= 2:
        delta = comparison.loc[seg_a] - comparison.loc[seg_b]
        comparison.loc[f'Delta ({seg_a} - {seg_b})'] = delta
    
    return comparison

# Ensure professional financial formatting
pd.options.display.float_format = '{:,.2f}'.format

In [32]:
# TEST 1: Full Dataset (No dates provided)
report_all = compare_segments(df2, 'Corporate', 'Consumer')
print(report_all)

 Analysis Period: Full Dataset
                              Avg_Sales  Total_Sales  Avg_Profit  Total_Profit
Segment
Consumer                         224.59 1,115,329.02       25.51    126,600.23
Corporate                        233.06   666,316.64       29.33     84,210.65
Delta (Corporate - Consumer)       8.47  -449,012.38        3.82    -42,389.58

In [33]:
# TEST 2: Specific range (Only 2017)
report_2017 = compare_segments(df2, 'Corporate', 'Consumer', start='2017-01-01', end='2017-12-31')
print(report_2017)

 Analysis Period: 2017-01-01 to 2017-12-31
                              Avg_Sales  Total_Sales  Avg_Profit  Total_Profit
Segment
Consumer                         201.27   320,616.29       27.28     43,540.65
Corporate                        251.39   235,547.94       26.12     24,525.51
Delta (Corporate - Consumer)      50.12   -85,068.35       -1.16    -19,015.14