In [34]:
import pandas as pd

df = pd.read_csv("../data/superstore.csv")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"42,420.00",South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"42,420.00",South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.582
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,"90,036.00",West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,NaN,...,"33,311.00",South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,NaN,-383.031
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,NaN,...,"33,311.00",South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.20,$2.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,"33,180.00",South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3.00,0.20,4.1028
9997,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,"92,627.00",West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.00,15.6332
9998,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,NaN,...,"92,627.00",West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.20,19.3932
9999,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,"92,627.00",West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6,4,0.00,13.32
10000,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,"92,683.00",West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.948

In [35]:
df.info()
print(df.shape)
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10001 non-null  int64
 1   Order ID       10001 non-null  object
 2   Order Date     10001 non-null  object
 3   Ship Date      10001 non-null  object
 4   Ship Mode      10001 non-null  object
 5   Customer ID    10001 non-null  object
 6   Customer Name  9617 non-null   object
 7   Segment        10001 non-null  object
 8   Country        10001 non-null  object
 9   City           9602 non-null   object
 10  State          9618 non-null   object
 11  Postal Code    9597 non-null   float64
 12  Region         10001 non-null  object
 13  Product ID     10001 non-null  object
 14  Category       10001 non-null  object
 15  Sub-Category   10001 non-null  object
 16  Product Name   9595 non-null   object
 17  Sales          10001 non-null  object
 18  Quantity       10001 non-null  object
 19  Discount       9632 non-null   float64
 20  Profit         10001 non-null  object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.6+ MB
(10001, 21)

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name    384
Segment            0
Country            0
City             399
State            383
Postal Code      404
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name     406
Sales              0
Quantity           0
Discount         369
Profit             0
dtype: int64

In [36]:
df.describe()

         Row ID  Postal Code  Discount
count 10,001.00     9,597.00  9,632.00
mean   4,997.05    55,187.28      0.16
std    2,884.83    32,047.91      0.21
min        1.00     1,040.00      0.00
25%    2,499.00    23,223.00      0.00
50%    4,998.00    56,301.00      0.20
75%    7,494.00    90,008.00      0.20
max    9,994.00    99,301.00      0.80

Due to the missing values of City represent less than 4% of the total data, we will drop the rows with missing values in the City column.

In [37]:
df = df.dropna(subset=['City'])
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"42,420.00",South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"42,420.00",South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.582
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,"90,036.00",West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.8714
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,"90,032.00",West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,"90,032.00",West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.28,4,0.00,1.9656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9989,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,"30,605.00",South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1,5,0.00,55.647
9996,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,"33,180.00",South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3.00,0.20,4.1028
9997,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,"92,627.00",West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.00,15.6332
9999,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,"92,627.00",West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6,4,0.00,13.32
10000,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,"92,683.00",West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.948

In [38]:
df.isna().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name    378
Segment            0
Country            0
City               0
State            371
Postal Code      390
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name     375
Sales              0
Quantity           0
Discount         353
Profit             0
dtype: int64

The missing values of Column name still in the dataset due to ......

In [39]:
df_final = df.copy()
df_final['Customer Name'] = df_final['Customer Name'].fillna('Unknown')

In [40]:
df_final.isna().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City               0
State            371
Postal Code      390
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name     375
Sales              0
Quantity           0
Discount         353
Profit             0
dtype: int64

In [41]:
df2 = df_final.copy()

# Convert Dates
df2['Order Date'] = pd.to_datetime(df2['Order Date'], format= 'mixed')
df2['Ship Date'] = pd.to_datetime(df2['Ship Date'], format= 'mixed')


# Convert Financials (Cleaning strings like '$1,200.00' first)
df2['Sales'] = pd.to_numeric(df2['Sales'].replace(r'[\$,]', '', regex=True), errors='coerce')
df2['Profit'] = pd.to_numeric(df2['Profit'].replace(r'[\$,]', '', regex=True), errors='coerce')

# Convert Quantity to Integer
df2['Quantity'] = pd.to_numeric(df2['Quantity'], errors='coerce').fillna(0).astype(int)

# Clean up Postal Code (removing decimal .0 and treating as string)
df2['Postal Code'] = df2['Postal Code'].fillna(0).astype(int).astype(str)

# Optimize Categorical columns
categorical_cols = ['Ship Mode', 'Segment', 'Region', 'Category', 'Sub-Category']
df2[categorical_cols] = df2[categorical_cols].astype('category')

# Verify the changes
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
Index: 9602 entries, 0 to 10000
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9602 non-null   int64
 1   Order ID       9602 non-null   object
 2   Order Date     9602 non-null   datetime64[ns]
 3   Ship Date      9602 non-null   datetime64[ns]
 4   Ship Mode      9602 non-null   category
 5   Customer ID    9602 non-null   object
 6   Customer Name  9602 non-null   object
 7   Segment        9602 non-null   category
 8   Country        9602 non-null   object
 9   City           9602 non-null   object
 10  State          9231 non-null   object
 11  Postal Code    9602 non-null   object
 12  Region         9602 non-null   category
 13  Product ID     9602 non-null   object
 14  Category       9602 non-null   category
 15  Sub-Category   9602 non-null   category
 16  Product Name   9227 non-null   object
 17  Sales          9525 non-null   float64
 18  Quantity       9602 non-null   int64
 19  Discount       9249 non-null   float64
 20  Profit         9529 non-null   float64
dtypes: category(5), datetime64[ns](2), float64(3), int64(2), object(9)
memory usage: 1.3+ MB
None

In [42]:
# Check for any dates that couldn't be parsed at all
print(f"Missing Order Dates: {df2['Order Date'].isna().sum()}")
print(f"Missing Ship Dates: {df2['Ship Date'].isna().sum()}")

Missing Order Dates: 0
Missing Ship Dates: 0

In [43]:
pd.options.display.float_format
def compare_segments(df, seg_a, seg_b):
   
    # Create a deep copy so the original df is untouched
    temp_df = df.copy()
    
    
    temp_df['Sales'] = pd.to_numeric(temp_df['Sales'].replace(r'[\$,]', '', regex=True), errors='coerce').fillna(0)
    temp_df['Profit'] = pd.to_numeric(temp_df['Profit'].replace(r'[\$,]', '', regex=True), errors='coerce').fillna(0)
    temp_df['Order Date'] = pd.to_datetime(temp_df['Order Date'], format='mixed')

    
    comparison = temp_df[temp_df['Segment'].isin([seg_a, seg_b])].groupby('Segment').agg(
        Avg_Profit=('Profit', 'mean'),
        Total_Sales=('Sales', 'sum')
    )
    
    
    delta = comparison.loc[seg_a] - comparison.loc[seg_b]
    comparison.loc[f'Difference ({seg_a} - {seg_b})'] = delta
    
    return comparison

In [47]:
pd.options.display.float_format = '{:,.2f}'.format

report = compare_segments(df2, 'Corporate', 'Consumer')


print("--- Strategy Consultant: Segment Comparison Report ---")
print(report)

--- Strategy Consultant: Segment Comparison Report ---
                                   Avg_Profit  Total_Sales
Segment
Consumer                                25.32 1,115,329.02
Corporate                               29.14   666,316.64
Home Office                               NaN         0.00
Difference (Corporate - Consumer)        3.82  -449,012.38

C:\Users\Usuario\AppData\Local\Temp\ipykernel_32596\3734320915.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  comparison = temp_df[temp_df['Segment'].isin([seg_a, seg_b])].groupby('Segment').agg(

In [48]:
import pandas as pd

def compare_segments_advanced(df, seg_a, seg_b, start=None, end=None):
    # 1. Use the requested default dates if none are provided
    # Default start: Jan 1st, 2024 | Default end: June 1st, 2018
    start_dt = pd.to_datetime(start) if start else pd.to_datetime('2024-01-01')
    end_dt = pd.to_datetime(end) if end else pd.to_datetime('2018-06-01')
    
    # 2. Chronological Check: Ensure the smaller date is always the 'start' for the filter
    # This handles the fact that Jan 2024 is after June 2018
    lower_bound = min(start_dt, end_dt)
    upper_bound = max(start_dt, end_dt)

    # 3. Filter using 'Order Date' and the selected Segments
    mask = (
        (df['Segment'].isin([seg_a, seg_b])) & 
        (df['Order Date'] >= lower_bound) & 
        (df['Order Date'] <= upper_bound)
    )
    df_filtered = df.loc[mask]

    # 4. Aggregate Metrics
    comparison = df_filtered.groupby('Segment', observed=False).agg(
        Avg_Profit=('Profit', 'mean'),
        Total_Sales=('Sales', 'sum')
    )

    # 5. Calculate Difference (Delta)
    if len(comparison) >= 2:
        delta = comparison.loc[seg_a] - comparison.loc[seg_b]
        comparison.loc[f'Delta ({seg_a} - {seg_b})'] = delta
    
    return comparison

# Apply the global format fix so the 'Total_Sales' looks like money
pd.options.display.float_format = '{:,.2f}'.format

# Try it out on your df_final
report = compare_segments_advanced(df2, 'Corporate', 'Consumer')
print(report)

                              Avg_Profit  Total_Sales
Segment
Consumer                             NaN         0.00
Corporate                            NaN         0.00
Home Office                          NaN         0.00
Delta (Corporate - Consumer)         NaN         0.00